global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dotnet-api'
    static_configs:
      - targets: ['agro-api:80']
    metrics_path: '/metrics'

  - job_name: 'zipkin'
    static_configs:
      - targets: ['zipkin:9411']