# This is a generated file. Not intended for manual editing.
services:
  agro-api:
    build:
      context: "/Users/vsevolodburtik/AgroManagementAPI"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/AgroManagementAPI.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "agromanagementapi:dev"
    ports: []
    volumes:
    - "/Users/vsevolodburtik/.nuget/packages:/root/.nuget/packages"
    - "/Users/vsevolodburtik/AgroManagementAPI:/app:rw"
    - "/Users/vsevolodburtik/AgroManagementAPI:/src:rw"
    working_dir: "/app"
